from enum import Enum


class Signaux(Enum):
    _GENERER_RESEAU = 1
    _LANCER_SIMULATION = 1.1
    _EXPORTER_XML = 1.2
    _CHARGER_XML = 1.3
    _EXPORTER_RESULTAT = 1.4

    _INITIALISATION_CREATION_GRAPHE = 2
    _INFORMATION_CREATION_GRAPHE = 2.1
    _AVANCEE_CREATION_GRAPHE = 2.2
    _FIN_CREATION_GRAPHE = 2.3

    _ANNULER_PARAMETRES = 3
    _VALIDER_PARAMETRES = 3.1
